# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "nvme_core.default_ps_max_latency_us=0" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7282b8e5-bf38-4746-b78f-c0c8ddc19e02";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "ssd"
      "compress=zstd:4"
      "noatime"
      "discard=async"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/7282b8e5-bf38-4746-b78f-c0c8ddc19e02";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "ssd"
      "compress=zstd:4"
      "noatime"
      "discard=async"
      "space_cache=v2"
      "commit=60"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FF64-2E3B";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/2c6e56bc-411e-4eed-9183-65ea65bcd1f2"; }
  ];

  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly";
    fileSystems = [ "/" ];
  };

  services.fstrim.enable = true;

  services.smartd = {
    enable = true;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
