{ pkgs, config, ... }:
{
  programs.dank-material-shell = {
    enable = true;
    enableDynamicTheming = true;
    niri.includes = {
      enable = true; # Enable config includes hack.
      override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
      originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
      filesToInclude = [
        # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
        "alttab" # Please note that niri will throw an error if any of these files are missing.
        "colors"
        "layout"
        "wpblur"
        "outputs"
      ];
    };
    systemd = {
      enable = true;
      restartIfChanged = true;
    };
  };
}
